name: Build For Android

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        float_precision: [single, double]
        target: [android]
        arch: [x86_64, arm64]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          # Define host for each target.
          - os: ubuntu-latest
            target: android

          # Define toolchain data.
          - target: android
            arch: arm64
            cmake_arch_keyword: arm64-v8a

          - target: android
            arch: x86_64
            cmake_arch_keyword: x86_64

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download IREE Host tools
        id: iree-dist
        uses: robinraju/release-downloader@v1.8
        with:
          filename: iree-dist-*-linux-x86_64.tar.xz
          repository: iree-org/iree
          tag: candidate-20240812.983
          extract: false

      - name: Extract IREE Host tools
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/iree-dist" ]; then
            mkdir "${{ github.workspace }}/iree-dist"
          fi
          tar -xf "${{ fromJson(steps.iree-dist.outputs.downloaded_files)[0] }}" -C "${{ github.workspace }}/iree-dist"

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Setup Android NDK
        id: android-ndk
        uses: nttld/setup-ndk@v1.4.2
        with:
          ndk-version: r25c

      - name: Set up CMake for Android
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/build" ]; then
            mkdir "${{ github.workspace }}/build"
          fi
          cd "${{ github.workspace }}/build"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type_keyword }} \
            -DIREE_HOST_BIN_DIR="${{ github.workspace }}/iree-dist/bin" \
            -DCMAKE_TOOLCHAIN_FILE="${{ steps.android-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=${{ matrix.cmake_arch_keyword }} \
            -DIREE_ENABLE_WERROR_FLAG=OFF \
            -DFLOAT_PRECISION=${{ matrix.float_precision }} \
            -DIREE_BUILD_SAMPLES=OFF \
            -DIREE_BUILD_TESTS=OFF

      - name: Build project
        shell: bash
        run: ninja -C "${{ github.workspace }}/build"

      - name: Show build files
        shell: bash
        working-directory: build
        run: ls -lR

      - name: Export artifact
        uses: actions/upload-artifact@v4
        with:
          name: iree-${{ matrix.float_precision }}-${{ matrix.target }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: |
            sample/**/*.so
            sample/**/*.gdextension
          if-no-files-found: error
