name: Build For Windows

on:
  push:
    branches:
      - "main"
      - "*-workflow"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target: [windows]
        arch: [x86_64]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          # Define host for each target.
          - os: windows-latest
            target: windows
            lib_suffix: lib

          # Define toolchain data.
          - target: windows
            arch: x86_64
            cmake_arch_keyword: x64

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set up MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@7315a94840631165970262a99c72cfb48a65d25d # v1.12.0
        with:
          arch: ${{ matrix.cmake_arch_keyword }}

      # Setup CMake
      - name: Set up CMake for Windows
        shell: cmd
        run: |
          if not exist "${{ github.workspace }}\\build" mkdir "${{ github.workspace }}\\build"
          cd "${{ github.workspace }}\\build"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE="${{ matrix.cmake_build_type_keyword }}"

      - name: Build project
        shell: bash
        run: cmake --build "${{ github.workspace }}/build"

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.target }}.${{ matrix.build_type }}.${{ matrix.arch }}"
          path: "${{ github.workspace }}\\build\\lib\\*iree-gd*.${{ matrix.lib_suffix}}"
          if-no-files-found: error
