name: Build For Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        float_precision: [single, double]
        target: [windows]
        arch: [x86_64]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          # Define host for each target.
          - os: windows-latest
            target: windows

          # Define toolchain data.
          - target: windows
            arch: x86_64
            cmake_arch_keyword: x64

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@7315a94840631165970262a99c72cfb48a65d25d # v1.12.0
        with:
          arch: ${{ matrix.cmake_arch_keyword }}

      # Setup CMake
      - name: Set up CMake for Windows
        shell: cmd
        run: |
          if not exist "${{ github.workspace }}\\build" mkdir "${{ github.workspace }}\\build"
          cd "${{ github.workspace }}\\build"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE="${{ matrix.cmake_build_type_keyword }}" -DIREE_ENABLE_WERROR_FLAG=OFF -DFLOAT_PRECISION=${{ matrix.float_precision }} -DIREE_BUILD_TESTS=OFF -DCOPY_LIBS_TO_SAMPLE=ON

      - name: Build project
        shell: bash
        run: cmake --build "${{ github.workspace }}\\build"

      - name: Show build files
        shell: bash
        working-directory: build
        run: ls -lR

      - name: Copy Files
        shell: bash
        run: |
          cp -rf "${{ github.workspace }}\\miscellaneous\\iree-gd.gdextension" "${{ github.workspace }}\\sample\\addons\\iree-gd\\iree-gd.gdextension"
          cp -rf "${{ github.workspace }}\\LICENSE" "${{ github.workspace }}\\sample\\addons\\iree-gd\\LICENSE"
          cp -rf "${{ github.workspace }}\\README.md" "${{ github.workspace }}\\sample\\addons\\iree-gd\\README.md"

      - name: Export libraries
        uses: actions/upload-artifact@v4
        with:
          name: iree-gd-${{ matrix.float_precision }}-${{ matrix.target }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: |
            ${{ github.workspace }}\sample\addons\iree-gd\*.dll
            ${{ github.workspace }}\sample\addons\iree-gd\iree-gd.gdextension
            ${{ github.workspace }}\sample\addons\iree-gd\LICENSE
            ${{ github.workspace }}\sample\addons\iree-gd\README.md
          if-no-files-found: error

      - name: Export samples
        uses: actions/upload-artifact@v4
        with:
          name: sample-iree-gd-${{ matrix.float_precision }}-${{ matrix.target }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: |
            ${{ github.workspace }}\sample
          if-no-files-found: error
