name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download iree-gd
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: runner.yml
          name: iree-gd
          skip_unpack: true

      - name: Download sample-iree-gd
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: runner.yml
          name: sample-iree-gd
          skip_unpack: true

      - name: Rename artifacts
        shell: bash
        run: |
          mv ${{ github.workspace }}/iree-gd.zip ${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip
          mv ${{ github.workspace }}/sample-iree-gd.zip ${{ github.workspace }}/sample-iree-gd-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip
            ${{ github.workspace }}/sample-iree-gd-${{ github.ref_name }}.zip
