name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download artifacts from Linux workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_linux.yml
          path: ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Download artifacts from Windows workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_windows.yml
          path: ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Download artifacts from MacOS workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_macos.yml
          path: ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Download artifacts from Android workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_android.yml
          path: ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Download artifacts from Linux ARM workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_linux_arm.yml
          path: ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Flatten directory
        shell: sh
        run: |
          cd ${{ github.workspace }}/sample/extensions/iree-gd
          find . -mindepth 2 -type f -exec sh -c 'exec mv "$@" .' sh {} +
          find . -mindepth 1 -type d -exec sh -c 'exec rm -rf "$@"' sh {} +

      - name: Copy Files
        shell: bash
        run: |
          cp ${{ github.workspace }}/CHANGELOG.md ${{ github.workspace }}/sample/extensions/iree-gd
          cp ${{ github.workspace }}/LICENSE ${{ github.workspace }}/sample/extensions/iree-gd
          cp ${{ github.workspace }}/README.md ${{ github.workspace }}/sample/extensions/iree-gd

      - name: Install zip utilities
        shell: bash
        run: |
          sudo apt update
          sudo apt install zip

      - name: Pack
        shell: bash
        run: |
          cd "${{ github.workspace }}/sample/extensions"
          zip -r "${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip" iree-gd
          cd "${{ github.workspace }}"
          zip -r "${{ github.workspace }}/iree-gd-sample-${{ github.ref_name }}.zip" sample

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip
            ${{ github.workspace }}/iree-gd-sample-${{ github.ref_name }}.zip
