name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: runner.yml

      - name: Copy Files
        shell: bash
        run: |
          cp -rf ${{ github.workspace }}/iree.gd/addons/iree-gd/* ${{ github.workspace }}/sample/addons/iree-gd
          cp -rf ${{ github.workspace }}/CHANGELOG.md ${{ github.workspace }}/sample/addons/iree-gd
          cp -rf ${{ github.workspace }}/LICENSE ${{ github.workspace }}/sample/addons/iree-gd
          cp -rf ${{ github.workspace }}/README.md ${{ github.workspace }}/sample/addons/iree-gd

      - name: Install zip utilities
        shell: bash
        run: |
          sudo apt update
          sudo apt install zip

      - name: Pack
        shell: bash
        run: |
          zip -r "${{ github.workspace }}/iree-gd-sample-${{ github.ref_name }}.zip" sample
          cd "${{ github.workspace }}/sample/addons"
          zip -r "${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip" iree-gd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/iree-gd-${{ github.ref_name }}.zip
            ${{ github.workspace }}/iree-gd-sample-${{ github.ref_name }}.zip
